services:
  redis:
    image: redis:7
    container_name: my-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    command:
      [
        'redis-server',
        '--requirepass',
        'your_redis_password',
        '--save',
        '60',
        '1',
        '--loglevel',
        'warning',
      ]
    restart: unless-stopped

volumes:
  redis-data:
